apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app-chart.fullname" . }}-result
  labels:
    {{- include "voting-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
    - port: {{ .Values.result.service.port }}
      targetPort: {{ .Values.result.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "voting-app-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: result
