apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app-chart.fullname" . }}-vote
  labels:
    {{- include "voting-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: vote
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "voting-app-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vote
